model:
  esm_encoder:
    model_name:  esm2_t33_650M_UR50D # esm2_t33_650M_UR50D, esm2_t30_150M_UR50D, esm2_t12_35M_UR50D, esm2_t6_8M_UR50D
    adapter_h:
      enable: True
      num_end_adapter_layers: 16
      module_type: "MLP1"
 